// <auto-generated />
using System;
using ClueGame.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClueGame.Migrations
{
    [DbContext(typeof(ClueDbContext))]
    [Migration("20250708205726_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClueGame.Models.Accusation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccusingPlayerId")
                        .HasColumnType("int");

                    b.Property<int?>("DisprovingCardId")
                        .HasColumnType("int");

                    b.Property<int?>("DisprovingPlayerId")
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("RoomCardId")
                        .HasColumnType("int");

                    b.Property<int>("SuspectCardId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("WeaponCardId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccusingPlayerId");

                    b.HasIndex("DisprovingCardId");

                    b.HasIndex("DisprovingPlayerId");

                    b.HasIndex("GameId");

                    b.HasIndex("RoomCardId");

                    b.HasIndex("SuspectCardId");

                    b.HasIndex("WeaponCardId");

                    b.ToTable("Accusations");
                });

            modelBuilder.Entity("ClueGame.Models.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("ClueGame.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CurrentTurnPlayerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("HumanCharacterId")
                        .HasColumnType("int");

                    b.Property<int>("SolutionRoomId")
                        .HasColumnType("int");

                    b.Property<int>("SolutionSuspectId")
                        .HasColumnType("int");

                    b.Property<int>("SolutionWeaponId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("StepsTaken")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CurrentTurnPlayerId");

                    b.HasIndex("HumanCharacterId");

                    b.HasIndex("SolutionRoomId");

                    b.HasIndex("SolutionSuspectId");

                    b.HasIndex("SolutionWeaponId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("ClueGame.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterCardId")
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlayerRoomId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CharacterCardId");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayerRoomId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("ClueGame.Models.PlayerCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CardId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerCards");
                });

            modelBuilder.Entity("ClueGame.Models.PlayerStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvgAccusations")
                        .HasColumnType("int");

                    b.Property<int>("AvgStepsTaken")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PlayerStats");
                });

            modelBuilder.Entity("ClueGame.Models.RoomAdjacency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RoomAId")
                        .HasColumnType("int");

                    b.Property<int>("RoomBId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoomAId");

                    b.HasIndex("RoomBId");

                    b.ToTable("RoomAdjacencies");
                });

            modelBuilder.Entity("ClueGame.Models.Accusation", b =>
                {
                    b.HasOne("ClueGame.Models.Player", "AccusingPlayer")
                        .WithMany()
                        .HasForeignKey("AccusingPlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClueGame.Models.Card", "DisprovingCard")
                        .WithMany()
                        .HasForeignKey("DisprovingCardId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ClueGame.Models.Player", "DisprovingPlayer")
                        .WithMany()
                        .HasForeignKey("DisprovingPlayerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ClueGame.Models.Game", "Game")
                        .WithMany("Accusations")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClueGame.Models.Card", "RoomCard")
                        .WithMany()
                        .HasForeignKey("RoomCardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClueGame.Models.Card", "SuspectCard")
                        .WithMany()
                        .HasForeignKey("SuspectCardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClueGame.Models.Card", "WeaponCard")
                        .WithMany()
                        .HasForeignKey("WeaponCardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AccusingPlayer");

                    b.Navigation("DisprovingCard");

                    b.Navigation("DisprovingPlayer");

                    b.Navigation("Game");

                    b.Navigation("RoomCard");

                    b.Navigation("SuspectCard");

                    b.Navigation("WeaponCard");
                });

            modelBuilder.Entity("ClueGame.Models.Game", b =>
                {
                    b.HasOne("ClueGame.Models.Player", "CurrentTurnPlayer")
                        .WithMany()
                        .HasForeignKey("CurrentTurnPlayerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ClueGame.Models.Card", "HumanCharacter")
                        .WithMany()
                        .HasForeignKey("HumanCharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClueGame.Models.Card", "SolutionRoom")
                        .WithMany()
                        .HasForeignKey("SolutionRoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClueGame.Models.Card", "SolutionSuspect")
                        .WithMany()
                        .HasForeignKey("SolutionSuspectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClueGame.Models.Card", "SolutionWeapon")
                        .WithMany()
                        .HasForeignKey("SolutionWeaponId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CurrentTurnPlayer");

                    b.Navigation("HumanCharacter");

                    b.Navigation("SolutionRoom");

                    b.Navigation("SolutionSuspect");

                    b.Navigation("SolutionWeapon");
                });

            modelBuilder.Entity("ClueGame.Models.Player", b =>
                {
                    b.HasOne("ClueGame.Models.Card", "CharacterCard")
                        .WithMany()
                        .HasForeignKey("CharacterCardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClueGame.Models.Game", "Game")
                        .WithMany("Players")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClueGame.Models.Card", "PlayerRoom")
                        .WithMany()
                        .HasForeignKey("PlayerRoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CharacterCard");

                    b.Navigation("Game");

                    b.Navigation("PlayerRoom");
                });

            modelBuilder.Entity("ClueGame.Models.PlayerCard", b =>
                {
                    b.HasOne("ClueGame.Models.Card", "Card")
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClueGame.Models.Player", "Player")
                        .WithMany("Cards")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("ClueGame.Models.RoomAdjacency", b =>
                {
                    b.HasOne("ClueGame.Models.Card", "RoomA")
                        .WithMany()
                        .HasForeignKey("RoomAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClueGame.Models.Card", "RoomB")
                        .WithMany()
                        .HasForeignKey("RoomBId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RoomA");

                    b.Navigation("RoomB");
                });

            modelBuilder.Entity("ClueGame.Models.Game", b =>
                {
                    b.Navigation("Accusations");

                    b.Navigation("Players");
                });

            modelBuilder.Entity("ClueGame.Models.Player", b =>
                {
                    b.Navigation("Cards");
                });
#pragma warning restore 612, 618
        }
    }
}
